server.port=8080
spring.application.name=prod-eng-service
mongodb.connection.url=${MONGODB_CONNECTION_URL:${MONGODB_CONECTION_URL:mongodb://root:example@localhost:27017}}
mongodb.database.name=${MONGODB_DATABASE_NAME:autoservice}
